spring:
  application:
    name: eureka-zuul
server:
  port: 8400

#eureka:
#  instance:
#    hostname: localhost
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  routes:
    service-ribbon:
      path: /ribbon/*
      serviceId: service-ribbon
    service-hi:
      path: /clients/*
      serviceId: service-hi
  host:
      maxTotalConnections: 10000
      maxPerRouteConnections: 10000
  semaphore:
      max-semaphores: 200
